USE DBSISTEMAUNIVERSIDAD
GO

INSERT INTO DEPARTAMENTO(NOMBRE) VALUES
('ANCASH'),
('LIMA')
GO

INSERT INTO PROVINCIA (COD_DEPARTAMENTO,NOMBRE) VALUES
(1,'PROV 1'),
(2,'PROV 2')
GO

SELECT * FROM DEPARTAMENTO
SELECT * FROM PROVINCIA
SELECT * FROM DISTRITO
SELECT * FROM PERSONA
SELECT * FROM USUARIO

DELETE FROM PROVINCIA WHERE NOMBRE='PROV 1'

INSERT INTO DISTRITO (COD_DEPARTAMENTO,COD_PROVINCIA,NOMBRE) VALUES (1,1,'SMP')

INSERT INTO PERSONA VALUES ('72190542',2,1,1,'ALFONSO','MOLERO','FARMAN','22/11/1990','M',29,'523','999','@','MZ')
INSERT INTO USUARIO VALUES ('U0000001','72190542',2,1,1,'ADM','USU','123','08/08/2002','ALFONSO','MOLERO','FARMAN','22/11/1990','M',29,'523','999','@','MZ')

SELECT * FROM PERSONA

DELETE FROM DISTRITO
DELETE FROM PROVINCIA
DELETE FROM DEPARTAMENTO

USE MASTER 
GO
DROP DATABASE DBSISTEMAUNIVERSIDAD

BORRAR LA SECCION Y SE TIENE QUE BORRAR LA MATRICULA
INSERTAR: ESCUELA, MALLA,CICLO,CURSO,SECCION Y MATRICULA

INSERT INTO ALUMNO VALUES('A1','72190542')
INSERT INTO FACULTAD VALUES('F1','FIIS',GETDATE())
INSERT INTO Escuela VALUES('E1', 'F1','EPIS',GETDATE())
INSERT INTO MALLA_CURRICULAR VALUES('M1','E1',10)
INSERT INTO CICLO VALUES ('C1','M1',1,1,1)
INSERT INTO CURSO VALUES('CU1','C1','INF',1,1)
INSERT INTO SECCION VALUES('S1','CU1','A',1)

INSERT INTO MATRICULA VALUES('MAT1','A1','E1','C1','CU1','S1',12)

SELECT * FROM ALUMNO
SELECT * FROM  FACULTAD
SELECT * FROM  Escuela
SELECT * FROM  MALLA_CURRICULAR
SELECT * FROM CICLO
SELECT * FROM CURSO
SELECT * FROM SECCION
SELECT * FROM MATRICULA

DELETE FROM SECCION
DELETE FROM ALUMNO
DELETE FROM ESCUELA
