CREATE DATABASE DBSISTEMAUNIVERSIDAD
GO

USE DBSISTEMAUNIVERSIDAD
GO


-----------------------------------------------------------------------------------
--							CREACIÓN DE TABLAS
-----------------------------------------------------------------------------------
--TABLA 1
CREATE TABLE DEPARTAMENTO
(
	COD_DEPARTAMENTO INT NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,

	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(COD_DEPARTAMENTO)
)
GO
--TABLA 2
CREATE TABLE PROVINCIA
(
	COD_PROVINCIA INT NOT NULL IDENTITY(1,1),
	COD_DEPARTAMENTO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_PROVINCIA PRIMARY KEY(COD_PROVINCIA)
)
GO

ALTER TABLE PROVINCIA 
ADD CONSTRAINT FK_PROVINCIA_DEPARTAMENTO FOREIGN KEY(COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 3
CREATE TABLE DISTRITO
(
	COD_DISTRITO INT NOT NULL IDENTITY(1,1),
	COD_PROVINCIA INT NOT NULL,
	COD_DEPARTAMENTO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,

	CONSTRAINT PK_DISTRITO PRIMARY KEY(COD_DISTRITO)
)
GO

ALTER TABLE DISTRITO
ADD CONSTRAINT FK_DISTRITO_DEPARTAMENTO FOREIGN KEY(COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO)
GO

ALTER TABLE DISTRITO
ADD CONSTRAINT FK_DISTRITO_PROVINCIA FOREIGN KEY(COD_PROVINCIA) REFERENCES PROVINCIA(COD_PROVINCIA)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 4
CREATE TABLE PERSONA
(
	DNI VARCHAR(8) NOT NULL,
	COD_DISTRITO INT NOT NULL,
	COD_PROVINCIA INT NOT NULL,
	COD_DEPARTAMENTO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO_PAT VARCHAR(30) NOT NULL,
	APELLIDO_MAT VARCHAR(30) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	SEXO VARCHAR(9) NOT NULL,
	EDAD INT NOT NULL,
	TELEFONO_FIJO VARCHAR(7),
	TELEFONO_CELULAR VARCHAR(9),
	EMAIL VARCHAR(70),
	DIRECCION VARCHAR(50) NOT NULL,

	CONSTRAINT PK_PERSONA PRIMARY KEY(DNI)
)
GO

ALTER TABLE PERSONA 
ADD CONSTRAINT FK_PERSONA_DEPARTAMENTO FOREIGN KEY(COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO)
GO

ALTER TABLE PERSONA 
ADD CONSTRAINT FK_PERSONA_PROVINCIA FOREIGN KEY(COD_PROVINCIA) REFERENCES PROVINCIA(COD_PROVINCIA)
GO

ALTER TABLE PERSONA 
ADD CONSTRAINT FK_PERSONA_DISTRITO FOREIGN KEY(COD_DISTRITO) REFERENCES DISTRITO(COD_DISTRITO)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 5
CREATE TABLE USUARIO
(
	COD_USUARIO VARCHAR(8) NOT NULL,
	DNI VARCHAR(8) NOT NULL,
	COD_DISTRITO INT NOT NULL,
	COD_PROVINCIA INT NOT NULL,
	COD_DEPARTAMENTO INT NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	NOMBRE_USUARIO VARCHAR(30) NOT NULL,
	CONTRASEÑA VARCHAR(30) NOT NULL,
	FECHA_REGISTRO DATE NOT NULL,
	NOMBRE VARCHAR(50),
	APELLIDO_PAT VARCHAR(30),
	APELLIDO_MAT VARCHAR(30),
	FECHA_NACIMIENTO DATE,
	SEXO VARCHAR(9),
	EDAD INT,
	TELEFONO_FIJO VARCHAR(7),
	TELEFONO_CELULAR VARCHAR(9),
	EMAIL VARCHAR(70),
	DIRECCION VARCHAR(50),

	CONSTRAINT PK_USUARIO PRIMARY KEY(COD_USUARIO)
)
GO

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY(DNI) REFERENCES PERSONA(DNI)
ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_DEPARTAMENTO FOREIGN KEY(COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO)
GO

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_PROVINCIA FOREIGN KEY(COD_PROVINCIA) REFERENCES PROVINCIA(COD_PROVINCIA)
GO

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_DISTRITO FOREIGN KEY(COD_DISTRITO) REFERENCES DISTRITO(COD_DISTRITO)
GO

ALTER TABLE USUARIO
ADD CONSTRAINT UQ_USUARIO_NOMBRE_USUARIO UNIQUE(NOMBRE_USUARIO)
GO

--TABLA 6
CREATE TABLE ADMINISTRADOR
(
	COD_ADMINISTRADOR VARCHAR(8) NOT NULL,
	DNI VARCHAR(8) NOT NULL,
	CARGO VARCHAR(30) NOT NULL,

	CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY(COD_ADMINISTRADOR)
)
GO

ALTER TABLE ADMINISTRADOR
ADD CONSTRAINT FK_ADMINISTRADOR_PERSONA FOREIGN KEY(DNI) REFERENCES PERSONA(DNI)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 7
CREATE TABLE ALUMNO 
(
	COD_ALUMNO VARCHAR(8) NOT NULL,
	DNI VARCHAR(8) NOT NULL,

	CONSTRAINT PK_ALUMNO PRIMARY KEY(COD_ALUMNO) 
)
GO

ALTER TABLE ALUMNO
ADD CONSTRAINT FK_ALUMNO_PERSONA FOREIGN KEY(DNI) REFERENCES PERSONA(DNI)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 8
CREATE TABLE DOCENTE
(
	COD_DOCENTE VARCHAR(8) NOT NULL,
	DNI VARCHAR(8) NOT NULL,
	COBRO_HORA REAL NOT NULL,

	CONSTRAINT PK_DOCENTE PRIMARY KEY(COD_DOCENTE) 
)
GO

ALTER TABLE DOCENTE
ADD CONSTRAINT FK_DOCENTE_PERSONA FOREIGN KEY(DNI) REFERENCES PERSONA(DNI)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 9
CREATE TABLE PROFESION
(
	COD_PROFESION VARCHAR(8) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,

	CONSTRAINT PK_PROFESION PRIMARY KEY(COD_PROFESION) 
)
GO

ALTER TABLE PROFESION
ADD CONSTRAINT UQ_PROFESION_NOMBRE UNIQUE(NOMBRE)
GO

--TABLA 10
CREATE TABLE PROFESION_ALUMNO
(
	COD_PROFESION_ALUMNO INT NOT NULL IDENTITY,
	COD_ALUMNO VARCHAR(8) NOT NULL,
	COD_PROFESION VARCHAR(8) NOT NULL,
	GRADO_ACADEMICO VARCHAR(30) NOT NULL,

	CONSTRAINT PK_PROFESION_ALUMNO PRIMARY KEY(COD_PROFESION_ALUMNO)
)
GO

ALTER TABLE PROFESION_ALUMNO
ADD CONSTRAINT FK_PROFESION_ALUMNO_ALUMNO FOREIGN KEY(COD_ALUMNO) REFERENCES ALUMNO(COD_ALUMNO)
ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE PROFESION_ALUMNO
ADD CONSTRAINT FK_PROFESION_ALUMNO_PROFESION FOREIGN KEY(COD_PROFESION) REFERENCES PROFESION(COD_PROFESION)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 11
CREATE TABLE PROFESION_DOCENTE
(
	COD_PROFESION_DOCENTE INT NOT NULL IDENTITY,
	COD_DOCENTE VARCHAR(8) NOT NULL,
	COD_PROFESION VARCHAR(8) NOT NULL,
	GRADO_ACADEMICO VARCHAR(30) NOT NULL,

	CONSTRAINT PK_PROFESION_DOCENTE PRIMARY KEY(COD_PROFESION_DOCENTE)
)
GO

ALTER TABLE PROFESION_DOCENTE
ADD CONSTRAINT FK_PROFESION_DOCENTE_DOCENTE FOREIGN KEY(COD_DOCENTE) REFERENCES DOCENTE(COD_DOCENTE)
ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE PROFESION_DOCENTE
ADD CONSTRAINT FK_PROFESION_DOCENTE_PROFESION FOREIGN KEY(COD_PROFESION) REFERENCES PROFESION(COD_PROFESION)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 12
CREATE TABLE FACULTAD
(
	COD_FACULTAD VARCHAR(8) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	FECHA_FUNDACION DATE NOT NULL,

	CONSTRAINT PK_FACULTAD PRIMARY KEY(COD_FACULTAD)
)
GO

--TABLA 13
CREATE TABLE ESCUELA
(
	COD_ESCUELA VARCHAR(8) NOT NULL,
	COD_FACULTAD VARCHAR(8) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	FECHA_FUNDACION DATE NOT NULL,

	CONSTRAINT PK_ESCUELA PRIMARY KEY(COD_ESCUELA)
)
GO

ALTER TABLE ESCUELA
ADD CONSTRAINT FK_ESCUELA_FACULTAD FOREIGN KEY(COD_FACULTAD) REFERENCES FACULTAD(COD_FACULTAD)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 14
CREATE TABLE MALLA_CURRICULAR
(
	COD_MALLA VARCHAR(8) NOT NULL,
	COD_ESCUELA VARCHAR(8) NOT NULL,
	CANTIDAD_CICLOS INT,

	CONSTRAINT PK_MALLA_CURRICULAR PRIMARY KEY(COD_MALLA)
)
GO

ALTER TABLE MALLA_CURRICULAR
ADD CONSTRAINT FK_MALLA_CURRICULAR_ESCUELA FOREIGN KEY(COD_ESCUELA) REFERENCES ESCUELA(COD_ESCUELA)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 15
CREATE TABLE CICLO
(
	COD_CICLO VARCHAR(8) NOT NULL,
	COD_MALLA VARCHAR(8) NOT NULL,
	NUMERO_CICLO INT NOT NULL,
	CANTIDAD_CURSOS INT,
	TOTAL_CREDITOS INT,


	CONSTRAINT PK_CICLO PRIMARY KEY(COD_CICLO)
)
GO

ALTER TABLE CICLO
ADD CONSTRAINT FK_CICLO_MALLA_CURRICULAR FOREIGN KEY(COD_MALLA) REFERENCES MALLA_CURRICULAR(COD_MALLA)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 16
CREATE TABLE CURSO
(
	COD_CURSO VARCHAR(8) NOT NULL,
	COD_CICLO VARCHAR(8) NOT NULL,
	NOMBRE VARCHAR(70) NOT NULL,
	CREDITOS INT,
	CUPOS INT NOT NULL,

	CONSTRAINT PK_CURSO PRIMARY KEY(COD_CURSO)
)
GO

ALTER TABLE CURSO
ADD CONSTRAINT FK_CURSO_CICLO FOREIGN KEY(COD_CICLO) REFERENCES CICLO(COD_CICLO)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 17
CREATE TABLE SECCION
(
	COD_SECCION VARCHAR(8) NOT NULL,
	COD_CURSO VARCHAR(8) NOT NULL,
	NOMBRE VARCHAR(5) NOT NULL,
	CUPOS INT NOT NULL,

	CONSTRAINT PK_SECCION PRIMARY KEY(COD_SECCION)
)
GO

ALTER TABLE SECCION
ADD CONSTRAINT FK_SECCION_CURSO FOREIGN KEY(COD_CURSO) REFERENCES CURSO(COD_CURSO)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 18
CREATE TABLE MATRICULA
(
	COD_MATRICULA VARCHAR(8) NOT NULL,
	COD_ALUMNO VARCHAR(8) NOT NULL,
	COD_ESCUELA VARCHAR(8) NOT NULL,
	COD_CICLO VARCHAR(8) NOT NULL,
	COD_CURSO VARCHAR(8) NOT NULL,
	COD_SECCION VARCHAR(8) NOT NULL,
	PAGO REAL,

	CONSTRAINT PK_MATRICULA PRIMARY KEY(COD_MATRICULA)
)
GO

ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_ALUMNO FOREIGN KEY(COD_ALUMNO) REFERENCES ALUMNO(COD_ALUMNO)
ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_ESCUELA FOREIGN KEY(COD_ESCUELA) REFERENCES ESCUELA(COD_ESCUELA)
GO

ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_CICLO FOREIGN KEY(COD_CICLO) REFERENCES CICLO(COD_CICLO)
GO

ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_CURSO FOREIGN KEY(COD_CURSO) REFERENCES CURSO(COD_CURSO)
GO

ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_SECCION FOREIGN KEY(COD_SECCION) REFERENCES SECCION(COD_SECCION)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 19
CREATE TABLE CONTRATO
(
	COD_CONTRATO VARCHAR(8) NOT NULL,
	COD_DOCENTE VARCHAR(8) NOT NULL,
	COD_ESCUELA VARCHAR(8) NOT NULL,
	SUELDO_CONTRATO REAL,

	CONSTRAINT PK_CONTRATO PRIMARY KEY(COD_CONTRATO)
)
GO

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONTRATO_DOCENTE FOREIGN KEY(COD_DOCENTE) REFERENCES DOCENTE(COD_DOCENTE)
ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONTRATO_ESCUELA FOREIGN KEY(COD_ESCUELA) REFERENCES ESCUELA(COD_ESCUELA)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 20
CREATE TABLE CALIFICACION
(
	COD_CALIFICACION VARCHAR(8) NOT NULL,
	COD_DOCENTE VARCHAR(8) NOT NULL,
	COD_CURSO VARCHAR(8) NOT NULL,
	EXAMEN_PARCIAL REAL,
	EXAMEN_FINAL REAL,
	PROMEDIO_PRACTICAS REAL,
	PROMEDIO_FINAL REAL,

	CONSTRAINT PK_CALIFICACION PRIMARY KEY(COD_CALIFICACION)
)
GO

ALTER TABLE CALIFICACION
ADD CONSTRAINT FK_CALIFICACION_DOCENTE FOREIGN KEY(COD_DOCENTE) REFERENCES DOCENTE(COD_DOCENTE)
ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE CALIFICACION
ADD CONSTRAINT FK_CALIFICACION_CURSO FOREIGN KEY(COD_CURSO) REFERENCES CURSO(COD_CURSO)
ON DELETE CASCADE ON UPDATE CASCADE
GO

--TABLA 21
CREATE TABLE DIAS_LABORALES
(
	COD_DIA_LABORAL INT NOT NULL,
	DIA VARCHAR(15) NOT NULL,

	CONSTRAINT PK_DIAS_LABORALES PRIMARY KEY(COD_DIA_LABORAL)
)
GO

--TABLA 22
CREATE TABLE CONTRATO_DIAS_LABORALES
(
	COD_CONTRATO_DIA_LABORAL INT NOT NULL IDENTITY,
	COD_CONTRATO VARCHAR(8) NOT NULL,
	COD_DIA_LABORAL INT NOT NULL,
	HORARIO VARCHAR(30),

	CONSTRAINT PK_CONTRATO_DIAS_LABORALES PRIMARY KEY(COD_CONTRATO_DIA_LABORAL)
)
GO

ALTER TABLE CONTRATO_DIAS_LABORALES
ADD CONSTRAINT FK_CONTRATO_DIAS_LABORALES_CONTRATO FOREIGN KEY(COD_CONTRATO) REFERENCES CONTRATO(COD_CONTRATO)
ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE CONTRATO_DIAS_LABORALES
ADD CONSTRAINT FK_CONTRATO_DIAS_LABORALES_DIAS_LABORALES FOREIGN KEY(COD_DIA_LABORAL) REFERENCES DIAS_LABORALES(COD_DIA_LABORAL)
ON DELETE CASCADE ON UPDATE CASCADE
GO

